"""Added disable field

Revision ID: 14f56207a2c4
Revises: 
Create Date: 2025-08-18 00:02:39.628172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f56207a2c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userbase', sa.Column('disabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.create_index(op.f('ix_userbase_disabled'), 'userbase', ['disabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userbase_disabled'), table_name='userbase')
    op.drop_column('userbase', 'disabled')
    # ### end Alembic commands ###
